baseURL = "https://mitmproxy.org/"
languageCode = "en-us"
title = "mitmproxy.org"
theme = "mitmproxy"
publishDir = "../public"
relativeURLs = true

[params]
  version = "9.0.0"

[indexes]
  tag = "tags"

[markup.goldmark.renderer]
unsafe = true
